// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: vehicle.proto

package vehicle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VehicleServiceClient is the client API for VehicleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehicleServiceClient interface {
	AddVehicle(ctx context.Context, in *Vehicle, opts ...grpc.CallOption) (*Vehicle, error)
	AddVehicleVerbose(ctx context.Context, in *Vehicle, opts ...grpc.CallOption) (VehicleService_AddVehicleVerboseClient, error)
}

type vehicleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleServiceClient(cc grpc.ClientConnInterface) VehicleServiceClient {
	return &vehicleServiceClient{cc}
}

func (c *vehicleServiceClient) AddVehicle(ctx context.Context, in *Vehicle, opts ...grpc.CallOption) (*Vehicle, error) {
	out := new(Vehicle)
	err := c.cc.Invoke(ctx, "/vehicle.VehicleService/AddVehicle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleServiceClient) AddVehicleVerbose(ctx context.Context, in *Vehicle, opts ...grpc.CallOption) (VehicleService_AddVehicleVerboseClient, error) {
	stream, err := c.cc.NewStream(ctx, &VehicleService_ServiceDesc.Streams[0], "/vehicle.VehicleService/AddVehicleVerbose", opts...)
	if err != nil {
		return nil, err
	}
	x := &vehicleServiceAddVehicleVerboseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VehicleService_AddVehicleVerboseClient interface {
	Recv() (*VehicleResultStream, error)
	grpc.ClientStream
}

type vehicleServiceAddVehicleVerboseClient struct {
	grpc.ClientStream
}

func (x *vehicleServiceAddVehicleVerboseClient) Recv() (*VehicleResultStream, error) {
	m := new(VehicleResultStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VehicleServiceServer is the server API for VehicleService service.
// All implementations must embed UnimplementedVehicleServiceServer
// for forward compatibility
type VehicleServiceServer interface {
	AddVehicle(context.Context, *Vehicle) (*Vehicle, error)
	AddVehicleVerbose(*Vehicle, VehicleService_AddVehicleVerboseServer) error
	mustEmbedUnimplementedVehicleServiceServer()
}

// UnimplementedVehicleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVehicleServiceServer struct {
}

func (UnimplementedVehicleServiceServer) AddVehicle(context.Context, *Vehicle) (*Vehicle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVehicle not implemented")
}
func (UnimplementedVehicleServiceServer) AddVehicleVerbose(*Vehicle, VehicleService_AddVehicleVerboseServer) error {
	return status.Errorf(codes.Unimplemented, "method AddVehicleVerbose not implemented")
}
func (UnimplementedVehicleServiceServer) mustEmbedUnimplementedVehicleServiceServer() {}

// UnsafeVehicleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleServiceServer will
// result in compilation errors.
type UnsafeVehicleServiceServer interface {
	mustEmbedUnimplementedVehicleServiceServer()
}

func RegisterVehicleServiceServer(s grpc.ServiceRegistrar, srv VehicleServiceServer) {
	s.RegisterService(&VehicleService_ServiceDesc, srv)
}

func _VehicleService_AddVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vehicle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServiceServer).AddVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vehicle.VehicleService/AddVehicle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServiceServer).AddVehicle(ctx, req.(*Vehicle))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleService_AddVehicleVerbose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Vehicle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VehicleServiceServer).AddVehicleVerbose(m, &vehicleServiceAddVehicleVerboseServer{stream})
}

type VehicleService_AddVehicleVerboseServer interface {
	Send(*VehicleResultStream) error
	grpc.ServerStream
}

type vehicleServiceAddVehicleVerboseServer struct {
	grpc.ServerStream
}

func (x *vehicleServiceAddVehicleVerboseServer) Send(m *VehicleResultStream) error {
	return x.ServerStream.SendMsg(m)
}

// VehicleService_ServiceDesc is the grpc.ServiceDesc for VehicleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vehicle.VehicleService",
	HandlerType: (*VehicleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVehicle",
			Handler:    _VehicleService_AddVehicle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddVehicleVerbose",
			Handler:       _VehicleService_AddVehicleVerbose_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vehicle.proto",
}
